CREATE TABLE IF NOT EXISTS user_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    event_id BIGINT,
    action_type VARCHAR,
    action_weight DOUBLE PRECISION,
    timestamp TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_action_user_timestamp
    ON user_action(user_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_user_action_event_timestamp
    ON user_action(event_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_user_action_type_timestamp
    ON user_action(action_type, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_user_action_timestamp
    ON user_action(timestamp DESC);


CREATE TABLE IF NOT EXISTS event_similarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a BIGINT,
    event_b BIGINT,
    score DOUBLE PRECISION,
    timestamp TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_similarity_a_score
    ON event_similarity(event_a, score DESC);
CREATE INDEX IF NOT EXISTS idx_event_similarity_b_score
    ON event_similarity(event_b, score DESC);
CREATE INDEX IF NOT EXISTS idx_event_similarity_high_score
    ON event_similarity(score DESC)
    WHERE score > 0.7;
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_event_similarity_unique_pair
--     ON event_similarity(event_a, event_b);