-- drop для разработки
DROP TABLE IF EXISTS comment CASCADE;

-- Comment
CREATE TABLE IF NOT EXISTS comment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        VARCHAR(4000) NOT NULL,
    status      VARCHAR(50) NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id    BIGINT, -- REFERENCES event(id) ON DELETE CASCADE NOT NULL,
    author_id   BIGINT --REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_comment_event_id_created ON comment(event_id, created DESC);
CREATE INDEX idx_comment_author_id_created ON comment(author_id, created DESC);
CREATE INDEX idx_comment_status_created ON comment(status, created DESC);
