-- drop для разработки
DROP TABLE IF EXISTS request CASCADE;

-- Request
CREATE TABLE IF NOT EXISTS request
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created         TIMESTAMP WITHOUT TIME ZONE,
    event_id        BIGINT, -- REFERENCES event(id) ON DELETE CASCADE NOT NULL,
    requester_id    BIGINT, -- REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    status          varchar(25) NOT NULL
 );
