-- drop для разработки
DROP TABLE IF EXISTS compilation_event CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;
DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;

-- Category
CREATE TABLE IF NOT EXISTS category
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_category_name ON category(name);

-- Compilation
CREATE TABLE IF NOT EXISTS compilation
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned  BOOLEAN,
    title   VARCHAR(255)
);

-- Location
CREATE TABLE IF NOT EXISTS location
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC(9,6) NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lon NUMERIC(9,6) NOT NULL CHECK (lon BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_location_lat on location(lat);
CREATE INDEX IF NOT EXISTS idx_location_lon on location(lon);
CREATE INDEX IF NOT EXISTS idx_location_coords on location(lat, lon);

-- Event
CREATE TABLE IF NOT EXISTS event
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(2000),
    category_id         BIGINT REFERENCES category(id) ON DELETE CASCADE,
    confirmed_requests  BIGINT,
    description         VARCHAR(7000),
    event_date          TIMESTAMP WITHOUT TIME ZONE,
    created_on          TIMESTAMP WITHOUT TIME ZONE,
    initiator_id        BIGINT,
    location_id         BIGINT REFERENCES location(id) ON DELETE CASCADE,
    paid                BOOLEAN,
    participant_limit   BIGINT,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(50),
    title               VARCHAR(120),
    views               BIGINT -- расчетное поле из сервиса статистики, в бд не пересчитывается
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT REFERENCES compilation (id) ON DELETE CASCADE NOT NULL,
    event_id       BIGINT REFERENCES event (id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);

-- Subscription
CREATE TABLE IF NOT EXISTS subscriptions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    subscriber_id BIGINT,
    UNIQUE(user_id, subscriber_id)
)